#region
using Av3Creator.Core;
using System.Linq;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;
using VRC.SDK3.Avatars.Components;
using Object = UnityEngine.Object;
#endregion

namespace Av3Creator.Utils
{
    public static class Av3Utils
    {
        public static VRCAvatarDescriptor SelectCurrentAvatar()
        {
            VRCAvatarDescriptor vrcAvatarDescriptor = null;
            if (Selection.activeTransform && Selection.activeTransform?.root?.gameObject?.GetComponent<VRCAvatarDescriptor>() != null)
            {
                vrcAvatarDescriptor = Selection.activeTransform.root.GetComponent<VRCAvatarDescriptor>();
                if (vrcAvatarDescriptor != null)
                    return vrcAvatarDescriptor;
            }

            var gameObjects = Object.FindObjectsOfType<VRCAvatarDescriptor>().OrderBy(x => x.transform.GetSiblingIndex()).ToArray();
            if (gameObjects != null && gameObjects.Length > 0)
            {
                if (gameObjects.Any(x => x.gameObject.activeSelf))
                    vrcAvatarDescriptor = gameObjects.First(x => x.gameObject.activeSelf);
                else vrcAvatarDescriptor = gameObjects.First();
            }

            return vrcAvatarDescriptor;
        }

        
        private static readonly string GeneratedA3CText = "Generated by A3C - Click here for more info!";
        public static void GenerateCredits(AnimatorController fxLayer)
        { 
            if (fxLayer.layers.Any(x => x.name == GeneratedA3CText)) fxLayer.RemoveLayer(GeneratedA3CText);

            fxLayer.AddLayer(GeneratedA3CText);
            var creditLayer = fxLayer.layers[fxLayer.layers.Length - 1];

            creditLayer.stateMachine.entryPosition = new Vector3(20, 0);
            creditLayer.stateMachine.anyStatePosition = creditLayer.stateMachine.entryPosition - new Vector3(220, 0);
            creditLayer.stateMachine.exitPosition = creditLayer.stateMachine.entryPosition + new Vector3(220, 0);

            void CreateState(string name, int x, int y) => EditorUtility.SetDirty(creditLayer.stateMachine.AddState(name, new Vector3(x, y)));

            CreateState("Toggles generated by Av3Creator!", 0, 50);
            CreateState("rafa booth pm", -105, 100);
            CreateState("rafacasari gumroad com", 105, 100);
        }
    }
}